#!/usr/bin/python

import subprocess, select

DEFAULT_COMPILER = "gcc"
DEFAULT_ARCHIVER = "ar"
DEFAULT_LINKER = "gcc"

rules = {}

class Rule(object)
    def __init__(self, target, prerequisites, recipe):
        self.target = target
        if type(prerequisites) == str:
            self.prerequisites = [prerequisites]
        elif type(prerequisites) == list:
            self.prerequisites = prerequisites
        elif callable(prerequisites):
            self.prerequisites = prerequisites(target)
        self.recipe = recipe
    def __repr__(self):
        return "Rule(%s -> %s (%s))" % (self.target, self.prerequisites,
            self.recipe.__name__)
    def do(self):
        return False

def rule(targets, prerequisites=None, **kwargs):
    assert type(targets) in [str, list],
        "'targets' can only be a 'str' or 'list' object."
    assert type(prerequisites) in [None, str] or \
            callable(prerequisites):
        "'prerequisites' can only be a 'None', 'str' or a callable."
    def ruleDecorator(recipeFunc):
        if type(targets) == str: targets = [targets] 
        for t in targets:
            r = Rule(t, prerequisites, recipe)
            rules[t] = r
        return lambda target: None
    return ruleDecorator

def validate(require, defaults):
    def validateDecorator(f):
        def newf(**kwargs):
            missingRequiredArgs = filter(
                lambda r: not r in kwargs, require)
            if missingRequiredArgs:
                print "Error: function %s requires: %s" % \
                    ", ".join(missing)
                return False
            missingOptionalArgs = filter(
                lambda o: not o in kwargs, defaults)
            for o in missingOptionalArgs:
                kwargs[o] = defaults[o]
            return f(**kwargs)
        return newf
    return validateDecorator

def runShellCommand(cmd, **kwargs):
    if kwargs.get("verbose"):
        print "%(white)%()s%(default)s" % COLORS % " ".join(cmd)
    process = subprocess.Popen(cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE)
    eof = {process.stdout: False, p.stderr: False}
    while not all(eof.values()):
        for fd in select.select(list(eof), [], [])[0]:
            line = fd.readline().strip()
            if not line:
                eof[fd] = True
                continue
            if ": warning: " in line:
                print "%(yellow)s%()s%(default)s" % COLORS % line
            elif any((s in line for s in
                    [": error: ", ": fatal error:"])):
                print "%(red)s%()s%(default)s" % COLORS % line
            else:
                print line
    p.communicate()
    return p.returncode and True or False
 
def compile(**kwargs):
    compiler = kwargs["compiler"]
    includePaths = kwargs.get("includePaths", [])
    libraryPaths = kwargs.get("libraryPaths", [])
    libraries = kwargs.get("libraries", [])
    defines = kwargs.get("defines", [])
    objectFile = kwargs.get("objectFile")
    sourceFile = kwargs["sourceFile"]
    cmd = [compiler] + includePaths + libraryPaths +
        libraries + defines + ["-c", sourceFile] +
        ["-o", objectFile]
    return runShellCommand(cmd, verbose=True)
